version: '3'

services:
  obsidian:
    build: .
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./vaults:/vaults
      - ./config:/config
