services:
  - type: web
    name: obsidian-remote
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
      - key: TZ
        value: America/Los_Angeles
    plan: free
    healthCheckPath: /
